HOST_CURSOR_SIZE=50
HOST_GTK_FONT='Victor Mono SemiBold 20'
HOST_BAR_FONT='Victor Mono SemiBold 26'
HOST_WALLPAPER="$HOME/Wallpapers/ghibli-fire-girl.jpg"
HOST_KITTY_FONT_SIZE=22
HOST_GHOSTTY_FONT_SIZE=24
HOST_MAKO_FONT='Dank Mono 24'
HOST_ROFI_FONT='Victor Mono SemiBold 30'
HOST_WOFI_FONT_SIZE=40px
HOST_MPV_PROFILE=''
HOST_MPV_GPU_API=''
HOST_MPV_CONTEXT=wayland
HOST_MPV_HWDEC=vaapi
HOST_MPV_SCALE='scale=bilinear'
HOST_MPV_CSCALE='cscale=bilinear'
HOST_MPV_DEBAND='deband=no'
HOST_MPV_VIDEO_SYNC='video-sync=display-resample'
HOST_MPV_INTERPOLATION='interpolation=no'
HOST_MPV_INTEROP=''
HOST_MPV_FAST=''
HOST_CHROMIUM_SCALE=1
