HOST_CURSOR_SIZE=34
HOST_GTK_FONT='Victor Mono SemiBold 14'
HOST_BAR_FONT='Victor Mono 20'
HOST_WALLPAPER="$HOME/Wallpapers/203553.jpg"
HOST_KITTY_FONT_SIZE=20
HOST_GHOSTTY_FONT_SIZE=20
HOST_MAKO_FONT='Victor Mono 18'
HOST_ROFI_FONT='Victor Mono SemiBold 20'
HOST_WOFI_FONT_SIZE=27px
HOST_MPV_PROFILE='profile=fast'
HOST_MPV_GPU_API='gpu-api=vulkan'
HOST_MPV_CONTEXT=waylandvk
HOST_MPV_HWDEC=vaapi
HOST_MPV_SCALE=''
HOST_MPV_CSCALE=''
HOST_MPV_DEBAND=''
HOST_MPV_VIDEO_SYNC=''
HOST_MPV_INTERPOLATION=''
HOST_MPV_INTEROP='gpu-hwdec-interop=vaapi'
HOST_MPV_FAST='vd-lavc-fast'
HOST_CHROMIUM_SCALE=1.33
