icons = "awesome5"
[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#03090e"
separator_bg = "#03090e"
idle_fg = "#e6e9ea"
info_bg = "#03090e"
info_fg = "#e6e9ea"
good_bg = "#03090e"
good_fg = "#e6e9ea"
warning_bg = "#03090e"
warning_fg = "#e6e9ea"
critical_bg = "#D12820"
critical_fg = "#e6e9ea"

[[block]]
block = "music"
max_width = 50
dynamic_width = true
smart_trim = true
buttons = []

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {ip}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used} /{mem_total}"
format_swap = "{swap_used} /{swap_total}"

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%m-%d-%Y %l:%M %p"
