[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#03090e"
separator_bg = "#03090e"
idle_fg = "#e6e9ea"
info_bg = "#03090e"
info_fg = "#e6e9ea"
good_bg = "#03090e"
good_fg = "#e6e9ea"
warning_bg = "#03090e"
warning_fg = "#e6e9ea"
critical_bg = "#D12820"
critical_fg = "#e6e9ea"

[icons]
icons = "awesome5"
[icons.overrides]
music = ""

[[block]]
block = "custom"
command = "sed 's/64129://' <(curl 'https://wttr.in/64129?u&format=3' -s)"
interval = 600

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:50,rot_interval:0.5) |}"

[[block]]
block = "net"
device = "wlan0"
format = "$ssid $ip|disconnected"

[[block]]
block = "github"
format = "$icon $total | $icon $mention | $icon $review_requested"
info = ["total"]
hide_if_total_is_zero = true
warning = ["mention","review_requested"]

[[block]]
block = "taskwarrior"
interval = 60
format = "$count open ($filter_name)"
format_everything_done = ""
warning_threshold = 10
critical_threshold = 20
[[block.filters]]
name = "today"
filter = "+PENDING +OVERDUE or +DUETODAY"

[[block]]
block = "memory"
format = "$mem_used / $mem_total"
format_alt ="$swap_used / $swap_total"

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 10
format = "$timestamp.datetime(f:'%m-%d-%Y %l:%M %p ')"
