[icons]
name = "awesome5"
[icons.overrides]
music = ""
[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#03090e"
separator_bg = "#03090e"
idle_fg = "#e6e9ea"
info_bg = "#03090e"
info_fg = "#e6e9ea"
good_bg = "#03090e"
good_fg = "#e6e9ea"
warning_bg = "#03090e"
warning_fg = "#e6e9ea"
critical_bg = "#D12820"
critical_fg = "#e6e9ea"

[[block]]
block = "music"
max_width = 50
dynamic_width = true
smart_trim = true
buttons = []

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {ip}"

[[block]]
block = "github"
format = "{total}|{mention}|{review_requested}"
info = ["total"]
hide_if_total_is_zero = true
warning = ["mention","review_requested"]

[[block]]
block = "taskwarrior"
interval = 60
format = "{count} open tasks ({filter_name})"
format_singular = "{count} open task ({filter_name})"
format_everything_done = "nothing to do!"
warning_threshold = 10
critical_threshold = 20
[[block.filters]]
name = "today"
filter = "+PENDING +OVERDUE or +DUETODAY"
[[block.filters]]
name = "WR"
filter = "project:WR +PENDING"

[[block]]
block = "bluetooth"
mac = "C8:91:9A:B1:F9:A8"
format = "MX {percentage}"
format_unavailable = ""

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used} /{mem_total}"
format_swap = "{swap_used} /{swap_total}"

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 10
format = "%m-%d-%Y %l:%M %p"
